#!/bin/bash
set -e

function luarocks
{
    luarocks-5.2 $@
}

new_version=$1

cd rockspecs
old_rockspec="$(ls -c | head -n 1)"
luarocks new_version $old_rockspec $new_version
new_rockspec="$(ls -c | head -n 1)"
luarocks lint $new_rockspec
cd ..
echo -n "Generated '$new_rockspec' from '$old_rockspec'.  Press return to continue ..." && read

git commit -m "Updated to $new_version"
git tag v$new_version
git push
git push --tags

cd rockspecs
luarocks upload $new_rockspec
cd ..
